### ISSUE TITLE
Rechtschreibung in Localisation-Datei

### ISSUE THREAD

**Issue by Chuck83** [stefanw/froide#127]
Da bei Anfragen auch immer so nett auf die Rechtschreibung hingewiesen wird:
Grußformeln werden nicht mit einem Komma vom darauffolgenden Namen abgetrennt.
Also: [Komma da weg!](http://www.stern.de/wissen/mensch/deutsche-rechtschreibung-komma-da-weg-1753879.html)

https://github.com/stefanw/froide/blob/master/locale/de/LC_MESSAGES/django.po#L3597
https://github.com/stefanw/froide/blob/master/locale/de/LC_MESSAGES/django.po#L3758

Vielen Dank für dieses Projekt und Deine Arbeit!

**Comment by stefanw** [comment]
Ist (endlich) passiert. Danke!
