### ISSUE TITLE
leeren Input failen lassen

### ISSUE THREAD

**Issue by ilf** [stefanw/froide#131]
Mindestens bei "Vermittlung einschalten" kann die Standard-Vorlage auch abgeschickt werden, wenn man sie nicht verändert. Jedoch steht im Textform (per default nicht sichtbar ohne scrollen), dieser halbe Satz. "Ich bin der Meinung, die Anfrage wurde zu unrecht abgelehnt, weil …"

Wäre schön, das Submit-Feld erst freizuschalten, wenn man den Vorgabetext editiert hat.

Evtl. auchmal checken, ob das auch bei anderen Input-Feldern so ist.

**Comment by arasabbasi** [comment]
Man könnte auch das "weil..." entfernen. Dann liefe das auf eine Generalüberprüfung hinaus.

**Comment by stefanw** [comment]
Ist gefixt.
