### ISSUE TITLE
verspätete Benachrichtigung durch fragdenstaat.de

### ISSUE THREAD

**Issue by HappyPony** [stefanw/froide#157]
Die Antwort der Behörde auf die Anfrage "Ergebnisse des Prüfvorgangs "Deutsche im Kampfeinsatz in der Ukraine"" https://fragdenstaat.de/a/11136 kam bereits am 25. August 2015 um 13:29 Uhr. Die Benachrichtigung von fragdenstaat.de habe ich in meinem Postfach erst am 01.09.2015 um 22:49 Uhr bekommen.

Ich rege an, die Ursache(n) für die verspätete Benachrichtigung durch fragdenstaat.de zu klären und Lösungsansätze für eine zeitnahe Zustellung von Benachrichtigungen durch fragdenstaat.de zu erarbeiten.

Ohne zeitnahe Zustellung von Benachrichtigungen hat fragdenstaat.de m.E. einen schlechten Stand, wenn es darum geht, Behörden davon zu überzeugen, dass fragdenstaat.de ein zuverlässiger EMail-Provider ist. Vgl. [1], [2].

[1] Agenda und mitgereiste Personen der Delegationsreise mit BM Gabriel im Iran [#10689], 04.08.2015 -  https://fragdenstaat.de/anfrage/agenda-und-mitgereiste-personen-der-delegationsreise-mit-bm-gabriel-im-iran/#nachricht-31478
[2] Anpassung Standard-Antwort auf FragDenStaat - "EchteMail" [#10947], 04.08.2015 - https://fragdenstaat.de/a/10947

**Comment by arnese** [comment]
Not a bug. Behörde hat Mail an falsche Adresse geschickt.

**Comment by HappyPony** [comment]
Es macht m.E. Sinn in solchen Fällen dem Anfrager den Sachverhalt "Behörde hat Mail an falsche Adresse geschickt." zu kommunizieren. Um u.a. Fragen, Postings wie https://github.com/stefanw/froide/issues/157 vorzubeugen.

**Comment by arnese** [comment]
Stimmt. Tschuldigung!
