### ISSUE TITLE
Die Buttons [Anfrage absenden] und [Bearbeiten Sie Ihre Anfrage noch mal] umplatzieren

### ISSUE THREAD

**Issue by HappyPony** [stefanw/froide#158]
ich rege an, die Buttons [Anfrage absenden] und [Bearbeiten Sie Ihre Anfrage noch mal] umgekehrt zu platzieren. Ich denke, dass wenn [Bearbeiten Sie Ihre Anfrage noch mal]-Schaltfläche besser erreichbar (in Klicknähe) ist, die Anfragen vor dem Absenden öfter geprüft und somit bessere Qualität haben.

**Comment by arnese** [comment]
Wird im Rahmen einer Usability-Analyse nochmal unter die Lupe genommen.
