### ISSUE TITLE
Anfrage erfolgreich, 1001 Jahre 

### ISSUE THREAD

**Issue by HappyPony** [stefanw/froide#159]
die Abfrage https://fragdenstaat.de/suche/?q=standard liefert in der Treffeliste auf Platz 1 
> Anforderung Dokument "Deutsche Standards für die nicht verwandte Blutstammzellspende" in Version 9 
> Anfrage erfolgreich, 1001 Jahre, 2 Monate her
https://fragdenstaat.de/a/8458

Sieht für mich wenig glaubwürdig aus ;-).

**Comment by arnese** [comment]
Ist kein Bug - der Nutzer hatte ein falsches Datum des Posteingangs eingegeben.
