### ISSUE TITLE
nice-to-have: Kurz-URL's auch für einzelne Postings ermöglichen

### ISSUE THREAD

**Issue by HappyPony** [stefanw/froide#160]
ich rege an, Kurz-URL's auch für einzelne Postings zu ermöglichen. Bspw. so: 
https://fragdenstaat.de/a/8458/#nachricht-23580
Ich verspreche mir von diesen Kurz-URL's die gleichen Vorteile, wie diese URL https://fragdenstaat.de/a/8458:
- platzsparend
- keine Zeilenumbrüche und so bessere Chancen, dass die URL bspw. in EMails funktioniert.

**Comment by arnese** [comment]
Ist bereits jetzt möglich: URL ist https://fragdenstaat.de/a/8458#nachricht-23580
