### ISSUE TITLE
400 Bad Request im Nutzungsbedingungen-Link

### ISSUE THREAD

**Issue by HappyPony** [stefanw/froide#163]
der Link 
> Tabelle zur Kostenschätzung

hier https://fragdenstaat.de/hilfe/nutzungsbedingungen/ 
im  Abschnitt 2.5 verursacht:

> 400 Bad Request

**Comment by stefanw** [comment]
Behoben. Bitte zukünftig solche Probleme mit FragDenStaat.de unter [okfde/fragdenstaat_de](https://github.com/okfde/fragdenstaat_de) anlegen.
