### ISSUE TITLE
KurzURL's mit Slash am Ende funktionieren nicht

### ISSUE THREAD

**Issue by HappyPony** [stefanw/froide#164]
der Link

> https://fragdenstaat.de/a/8528/

meldet 

> 404 - Nicht Gefunden

Der Link

> https://fragdenstaat.de/a/8528

dagegen geht. Ich rege an,  dass KurzURL's mit Slash am Ende auch funktionsfähig gemacht werden.

**Comment by stefanw** [comment]
The question is: why? Short URLs do not usually end with a slash (e.g. see t.co links) – which makes them... well... shorter. In fact Twitter short URLs do not work with a slash appended.

**Comment by tzwenn** [comment]
True. How was the above link created in the first place? Did some other crazy tool on the way (browser, mailclient, notes app, etc) mess with it?
In that undesirable case you could argue all froide-links should be able to end in /. (Is this plausible or feasible?)

Or it might be human-created in consistent analogy to almost all other links in `froide.urls` ending that way.

**Comment by HappyPony** [comment]
ok. ich ziehe meinen Vorschlag zurück. danke für das Feeedback.
