### ISSUE TITLE
Namen  vertauscht

### ISSUE THREAD

**Issue by HappyPony** [stefanw/froide#165]
Die Namen Edward Sommer und  Gustav Wall sind verkehrt herum im Vergleich zur tatsächlichen  Reihenfolge von Postings in dieser EMail von der fragdenstaat.de-Plattform:
<pre>
Betreff: Frag den Staat: Neues bei einer Anfrage, die Sie interessiert
Datum: Sun, 13 Sep 2015 22:00:00 -0000
Von: 
An: 

Hallo Gustav Wall,

in den letzten 24 Stunden passierte Folgendes bei einer Anfrage, der Sie folgen.

Neues bei Anfrage "Kosten des Rechtsstreites zum IFG (Bundestags-Hausausweise)":
- 04:55: Neuer Kommentar von Edward Sommer
- 09:34: Neuer Kommentar von Gustav Wall

Gehen Sie zu der Anfrage:
https://fragdenstaat.de/a/10336

Wenn Sie diese Anfrage NICHT mehr interessiert, klicken Sie diesen Link:
https://fragdenstaat.de/benachrichtigen/keine-benachrichtigungen-erhalten/4984/b010e21d6cf0f164734185e19669e72b/
</pre>

**Comment by arnese** [comment]
Stimmt nicht - Beide Kommentare sind auf der Seite abgefasst worden. Nicht direkt untereinander, aber Zeitbezeichnungen sind korrekt.

**Comment by HappyPony** [comment]
> Stimmt nicht - Beide Kommentare sind auf der Seite abgefasst worden. Nicht direkt untereinander, aber Zeitbezeichnungen sind korrekt.

Zeitbezeichnungen sind auf https://fragdenstaat.de/a/10336 korrekt. Aber in der EMail - s. oben - sind die Namen in den Zeitbezeichnungen vertauscht.

Ich weiss doch, dass ich früher als Edward Sommer kommentiert habe. Sieht man auch hier  https://fragdenstaat.de/a/10336 .

**Comment by arnese** [comment]
Der Kommentar um 9:36 ist allerdings dieser: https://fragdenstaat.de/anfrage/kosten-des-rechtsstreites-zum-ifg-bundestags-hausausweise/#nachricht-31207
