### ISSUE TITLE
Comparison to Alaveteli

### ISSUE THREAD

**Issue by dotlambda** [stefanw/froide#182]
It would be nice to point out how Froide compares to [Alaveteli](https://github.com/mysociety/alaveteli/) in the README or in this issue.
Why exactly did the OKF write their own software?

**Comment by stefanw** [comment]
When [FragDenStaat.de](https://fragdenstaat.de/) (the first project powered by froide) started in 2011, Alaveteli was not ready yet and still full of code specific to <https://whatdotheyknow.com> and had no i18n.

We also needed features in Germany that were not needed in the UK and therefore not present in alaveteli. These feature were for example hiding recipient names, multiple jurisdictions with different laws, uploading of documents and redaction of attachments. I'm also not a RoR person (and the RoR code was in bad shape back then afaik). If you have any more questions, let me know.
