### ISSUE TITLE
Test suite needs phantomjs installed

### ISSUE THREAD

**Issue by pdehaye** [stefanw/froide#185]
PhantomJS is not listed as a requirement, but at least one test fails without it.

**Comment by stefanw** [comment]
Correct, `phantomjs` is the default `selenium` driver. You can switch out the default selenium driver by setting the environment variable or Django setting `TEST_SELENIUM_DRIVER`. Other options are currently "firefox" or "chrome". [More details here](https://github.com/stefanw/froide/blob/master/froide/tests/live/test_request.py#L18-L28). Please add documentation where you would expected this information and open a pull request.

**Comment by pdehaye** [comment]
I don't think this fully addresses the issue. I applied the first two commands [here](http://froide.readthedocs.io/en/latest/development/?highlight=tests):

`pip install -r requirements-test.txt` then `make test`, and that failed for at least one because phantomJS wasn't installed as part of the requirements. I would have expected it to be, but it doesn't look trivial to automate (dependent on the platform, I am on mac).
