### ISSUE TITLE
Quality reduction of attachments in zip

### ISSUE THREAD

**Issue by GiantCrocodile** [stefanw/froide#190]
If you download an inquiry the zip file contains only a low quality copy of attachments. Quality shouldn't be reduced at all simply because it may render some smaller text unreadable and makes printing harder.

**Comment by stefanw** [comment]
That shouldn't be the case. (Froide attaches the original, non-redacted, non-converted attachments)[https://github.com/stefanw/froide/blob/master/froide/foirequest/foi_mail.py#L222-L225]. Can you point to a case somewhere?
