### ISSUE TITLE
Filenames are wrong in zip file

### ISSUE THREAD

**Issue by GiantCrocodile** [stefanw/froide#191]
I have a zip file with these files in:

- yyyy-mm-dd_1_anfragesteller.txt
- yyyy-mm-dd_1_behoerde.txt
- yyyy-mm-dd_1_anfragesteller.txt
- yyyy-mm-dd_2_behoerde.txt
- yyyy-mm-dd_3_anfragesteller.txt

I think the third file should be named yyyy-mm-dd_2_anfragesteller.txt.

**Comment by stefanw** [comment]
The digits behind the date are only incremented for the same date ([see the ugly details here](https://github.com/stefanw/froide/blob/master/froide/foirequest/foi_mail.py#L213-L220)). It's certainly not the nicest solution, but I wouldn't call it wrong. Please open a PR if you want to contribute a better solution.
