### ISSUE TITLE
Warn user if a state/region has a minimum fee for every request

### ISSUE THREAD

**Issue by GiantCrocodile** [stefanw/froide#196]
An user should be warned if he/she creates an inquiry to an authority/agency in a state or region where there is a minimum fee for every request (so no free inquiries possible).

**Comment by arnese** [comment]
That already happens in Berlin. Is there another state we missed?

**Comment by GiantCrocodile** [comment]
Yes Hamburg has a minimum of 15 Euro as far as I know.

**Comment by arnese** [comment]
No: https://www.datenschutz-hamburg.de/uploads/media/Gebuehrenordnung_Transparenzgesetz_HmbTGGebO.pdf - Einfache Auskünfte sind gebührenfrei § 1 (3).
Übersicht hier: https://fragdenstaat.de/hilfe/gebuehren/
