### ISSUE TITLE
Add a contact form

### ISSUE THREAD

**Issue by GiantCrocodile** [stefanw/froide#197]
It would be nice to see a contact form to send e-mails to the website admin. This will help people who have no e-mail client or are not that internet affine to get in touch with admin to report site issues, suggest improvements or to ask for help. The contact form should be located in the footer or header.

**Comment by fin** [comment]
i'm against doing this in froide.
the system is hard to maintain as-is, in my opinion this should be added by a theme, if a site decides to add it

**Comment by GiantCrocodile** [comment]
Hard to maintain regarding @fin? I'm talking from a point of view of an end user. So I can't evaluate this from point of view of an admin of a Froide site.

**Comment by stefanw** [comment]
@fin is right, I actually want to slim down froide as much as possible and move features to external apps.

Please move any suggestions for features that should be added to specific sites using froide (e.g. fragdenstaat.de) to their respective repository (e.g. https://github.com/okfde/fragdenstaat_de).
