### ISSUE TITLE
Make Tags in URL case-insensitive

### ISSUE THREAD

**Issue by GiantCrocodile** [stefanw/froide#208]
If I search for tag 'Bundeswehr' via URL https://fragdenstaat.de/anfragen/tag/bundeswehr/ it doesn't work: 404 error. But if I change it to 'bundeswehr' it is found. The tags should be case-insensitive in URLs.

**Comment by stefanw** [comment]
Sorry, this is not how the tag URLs work. Froide is using the third-party library `django-taggit`. Tags have a name and a slug and going to a URL will do an exact lookup on the slug. A search is not performed.

This is not to say that Froide couldn't do with a better search that also includes tags.
